POST {{host}}/api/registry-save HTTP/1.1
content-type: application/json
Cookie: {{cookie}}

{
    "rescate": 0,
    "fiebre": 1,
    "constipacion":0,
    "cansancio":1,
    "nausea":5,
    "apetito":5,
    "aire":5,
    "tragar":5,
    "painlevel": 3
}
